### ISSUE TITLE
Adding Logitech G29 functionality 

### ISSUE THREAD

**Issue by zhgqfqxzdm** [BroGamer4256/WanganArcadeLoader#2]
I can't seem to find the answer to this.  Is there a way to add controls functionality for a PS/PC version of the Logitech G29 wheel, pedal, & shifter?  I see the file to edit the controls but with no knowledge of what settings to change for what options.

**Comment by vixen256** [comment]
Yes

**Comment by zhgqfqxzdm** [comment]
any guidance on how to do so?

**Comment by vixen256** [comment]
Look at [GameControllerDb](https://github.com/mdqinc/SDL_GameControllerDB)
This is my personal G29 setup
`0300f04c6d0400004fc2000011010000,Logitech G29 Driving Force Racing Wheel,a:b0,b:b2,x:b1,y:b3,back:b8,guide:b24,start:b9,leftshoulder:b5,rightshoulder:b4,leftstick:b11,rightstick:b10,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,-leftx:-a0,+leftx:+a0,righttrigger:-a2,lefttrigger:+a2,platform:Linux,`

**Comment by zhgqfqxzdm** [comment]
I hate to bother you again but I have a question.  would you happen to have
build instructions that you could add to the readme or give me any pointers
on how to compile it?  I'm just trying to teach myself a little bit &
decided to try compiling myself just to see if I could learn to do it on my
own, and no matter what command I try, I get a build error at some point.
I've tried make, meson build, & meson compile.  Any help or instructions
would be greatly appreciated.  Thanks
