### ISSUE TITLE
Loader doesn't work properly game has a online check function

### ISSUE THREAD

**Issue by Revenger** [BroGamer4256/WanganArcadeLoader#3]
When I first unzipped I could load fine now I get this error after a couple weeks.
Updating the loader doesn't do anything.
Game is saying as it hasn't connected to the network for a while it cannot start so has some form of network DRM still embedded.

![image](https://github.com/user-attachments/assets/64d634b1-e053-40d5-9dd5-2806948ab787)

![image](https://github.com/user-attachments/assets/249d17ad-848e-4bf2-bdf8-2391535ffd84)

**Comment by doomertheboomer** [comment]
find operation_w6w.bin.gz and delete it

**Comment by vixen256** [comment]
The game has no DRM, it just expects to be connected to a server and has near no functionality without one, I'd suggest you find one online.

**Comment by Revenger** [comment]
> find operation_w6w.bin.gz and delete it

This got me into local single player offline mode..
File is in the games main directory.
So the  game uses this file to check for connectivity or something and if it's been too long since it last connected to the servers it locks you out of loading with E0552.
Don't know how long the offline grace period is with the file,
Will have to look for various server stuff to get the extra functionality.,

And @BroGamer4256 this is much the same as games and apps with a offline mode time limit when you switch to that offline mode that need to phone home every 14 days or so else it revokes your access.

Berceuse versions we have the cabinet serials are obviously revoked etc so it cant connect to official servers to verify official identity hence the E0552, just so happened they gave a initial grace period without the operation file present.
Just with this game deleting that file resets the time limit.

Looking online at Project Asuka E0554 and E0551 is a similar certificate error as that is a certificate which updates from the server and expires after some time.
The game itself has an initial grace period of probably about a couple of weeks before needing to update or acquire a certificate from the server.
